// Code generated by protoc-gen-go. DO NOT EDIT (stub for training repo).
// In real usage: run `make proto` from reference-implementation/.
//
// This stub exists so you can read the service code without setting up protoc immediately.
package ordersv1

import (
  context "context"
  grpc "google.golang.org/grpc"
)

type CreateOrderRequest struct {
  CustomerId string
  ItemIds    []string
}
func (x *CreateOrderRequest) GetCustomerId() string { return x.CustomerId }
func (x *CreateOrderRequest) GetItemIds() []string  { return x.ItemIds }

type CreateOrderResponse struct {
  OrderId string
}
func (x *CreateOrderResponse) GetOrderId() string { return x.OrderId }

type OrdersServiceServer interface {
  CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
}
type UnimplementedOrdersServiceServer struct{}
func (UnimplementedOrdersServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
  return nil, grpc.Errorf(grpc.Code(grpc.ErrServerStopped), "not implemented")
}

func RegisterOrdersServiceServer(s grpc.ServiceRegistrar, srv OrdersServiceServer) {}
