flowchart TB
  subgraph "Catalog Context"
    C1[Catalog Service]
    CDB[(Catalog DB)]
    C1-->CDB
  end

  subgraph "Orders Context"
    O1[Orders Service]
    ODB[(Orders DB)]
    O1-->ODB
  end

  C1-- ProductUpdated event -->O1
  O1-- OrderPlaced event -->C1
